services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nanogpt-api
    environment:
      DEVICE: cpu
      MODEL_PATH: results/colab-checkpoints/exp1_step5000.pt
      TOKENIZER_PATH: data/tokenizer.json
      RESULTS_DIR: results
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - mlflow

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: nanogpt-dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - api

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.1
    container_name: nanogpt-mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./results/mlflow:/mlflow
    restart: unless-stopped
